export enum Property {
  ALBUM_ID = 'albumId',
  ARTIST_ID = 'artistId',
  CATEGORY = 'category',
  CRITERIA = 'criteria',
  DURATION = 'duration',
  EVENT = 'event',
  GENRE = 'genre',
  GRAMMY = 'grammy',
  LOGIN = 'login',
  MOOD = 'mood',
  NAME = 'name',
  NEW_PASSWORD = 'newPassword',
  OLD_PASSWORD = 'oldPassword',
  OPTIONAL = 'optional',
  PASSWORD = 'password',
  TAGS = 'tags',
  USER_ID = 'userId',
  USERNAME = 'userName',
  YEAR = 'year',
}
